#!/usr/bin/env bash
# args: window instance, something to pgrep for, startup command

# Launch program if it's not running
# Show program if it's hidden
# Move all windows of a program to this workspace if it's only visible somewhere else
# Hide all windows of a program if any are visible on this workspace

# $1 - window class
# $2 - executable name
# $3 - startup command
# $4 - optional: working directory
set -e

class=$1

if [[ $4 != "" ]]; then
  cd "$4"
fi

count=$(pgrep -u $USER -f -c "$2$") || true
if [[ $count < 2 ]]; then
  $($3) &
  exit
fi

exit 0
wid=$(xdotool search --all --onlyvisible --desktop $(xprop -notype -root _NET_CURRENT_DESKTOP | cut -c 24-) --classname "$class" || test $? = 1)
if [[ $wid != "" ]]; then
  swaymsg [instance="$class"] move scratchpad > /dev/null
  exit
fi

swaymsg [instance="$class"] move workspace current > /dev/null
swaymsg [instance="$class"] focus
