# Currently most of these are specific to Mangadex. The config format will
# change if more sites are supported.

# Language code used by Mangadex. Must be set.
language = "en"

# Directory where all the manga will be stored.
# The directory must already exist.
# Existing files in the directory will not be touched but manually deleting
# chapters will cause them to be redownloaded.
output_directory = "/storage/media/manga"

# Directory to store temporary files, leave blank for the system default.
temp_directory = '/tmp'

# Whether or not chapter archives should be renamed.
# This can be relevant when volume numbering is revised later.
rename_chapters = true
rename_manga = true

# Whether to allow question marks in file names or not.
# Most operating systems allow question marks in file names.
# Windows does not, files cannot be created or read if their names contain question marks.
#
# DO NOT ENABLE THIS ON WINDOWS
allow_question_marks = true

# Groups to block, for low quality or other reasons.
blocked_groups = [
  "4fdaf04f-b965-4f82-801d-8bfc00693773",
  "9dcf0896-a184-4cbc-8070-751bb71c5f2e",
  "fb26969d-0365-4944-831a-5b8a3d471e94",
]

# The number of pages to download in parallel
# Do not set it too high.
parallel_downloads = 8

