# Used for desktop screenshots and when the window name can't be determined
Fallback = 'desktop'
ScreenshotDir = '/storage/public/shots'

# Will be ignored in favour of any available children
# Note that gnome-terminal is uniquely incapable and doesn't set WINDOWID
IgnoredParents = ['kitty', 'xfce4-terminal', 'zsh', 'alacritty', 'bash']

# Uncomment to check for WINDOWID if you're using a terminal that doesn't use
# separate processes per window. Doesn't help with gnome-terminal.
CheckWindowID = true

# Callback will be called with the path to screenshot.
Callback = 'public-clipboard'

# PNG compression level in the range of 0-9
# 0 is fastest, 9 is slowest
# 8 and 9 are slow enough to be annoying for interactive usage
# 0 compresses too poorly to use and saves little time over 1
Compression = 5

# Additional shaders to use with slop.
# See https://github.com/naelstrof/slop/tree/master/shaderexamples
SlopShaders = ['boxzoom']

# Overrides. The first one with a matching name and Regex is used.
#
# Name: The application name to match against. Multiple overrides can be
# specified for a name.
#
# TODO -- Regex
# Regex: If present, the full command line is matched against this RE.
# Leave blank to match every instance of Name. Regex can't match every window,
# some windows have no pids so we use the name instead.
#
# Format: The output pattern. Use %s to reference the groups from any regex
# match.

[[Overrides]]
  Name = "vimx"
  Format = "vim"

[[Overrides]]
  Name = "gvim"
  Format = "vim"

[[Overrides]]
  Name = "i3"
  Format = "desktop"

[[Overrides]]
  Name = "chromium-browser"
  Format = "chromium"

[[Overrides]]
  Name = "wine32-preloader"
  Regex = 'TLS.*Game.exe$'
  Format = "the-last-sovereign"

[[Overrides]]
  Name = "wine32-preloader"
  Regex = '^(.*(/|\\))?([^/]+) \d\.\d\d\d[[:lower:]]?\\Game.exe'
  Format = "%[4]s"

[[Overrides]]
  Name = "wine32-preloader"
  Regex = '^(.*(/|\\))?([^/]+) ?\d\.?\d\.?\d[[:lower:]]?\\Game.exe'
  Format = "%[4]s"

[[Overrides]]
  Name = "wine32-preloader"
  Regex = '^(.*(/|\\))?([^/]+)\\Game.exe'
  Format = "%[4]s"

[[Overrides]]
  Name = "wine32-preloader"
  Regex = '^(.*(/|\\))?([^/\ ]+)\.exe'
  Format = "%[4]s"

[[Overrides]]
  Name = "nw"
  Regex = '^(.*(/))?([^/]+) V\.\d+\(:alpha:\) Linux/nw'
  Format = "%[3]s"

[[Overrides]]
  Name = "nw"
  Regex = '^(.*(/))?([^/]+)/nw'
  Format = "%[3]s"

[[Overrides]]
  Regex = 'bin/mcomix '
  Delegate = "/home/desuwa/.config/screenshotter/mcomix-manga.sh"

[[Overrides]]
  Regex = 'bin/mcomix '
  Format = "mcomix"
  Yearly = true

[[Overrides]]
  Regex = '^/usr/bin/python(\d(.\d)?)? .*/\.?bin/([^/ ]+)( .*)?'
  Format = "%[4]s"

[[Overrides]]
  Name = "watch"
  Regex = '^watch ([^ ]*)?'
  Format = "%[2]s"

[[Overrides]]
  Name = "firefox"
  Delegate = "/home/desuwa/.config/screenshotter/firefox-mangadex.sh"

[[Overrides]]
  Name = "firefox"
  Delegate = "/home/desuwa/.config/screenshotter/firefox-mangaplus.sh"

[[Overrides]]
  Name = "firefox"
  Delegate = "/home/desuwa/.config/screenshotter/firefox-ptscans.sh"

[[Overrides]]
  Name = "mpv"
  Delegate = "/home/desuwa/.config/screenshotter/mpv-anime.sh"

[[Overrides]]
  Name = "firefox"
  Yearly = true

[[Overrides]]
  Name = "mpv"
  Yearly = true

[[Overrides]]
  Name = "wine-preloader"
  Regex = 'noratoto1.exe$'
  Format = "Nora to Oujo to Noraneko Heart"

[[Overrides]]
  Name = "ppssppqt"
  Delegate = "/home/desuwa/.config/screenshotter/ppsspp.sh"
  Callback = "/home/desuwa/.config/screenshotter/ppsspp-callback.sh"
