#!/bin/sh
# ~/.cron/certbot-renew

set -e

# The following directories must exist and be writeable by the user running this
config_dir=/usr/local/etc/letsencrypt
logs_dir=/usr/local/var/log/letsencrypt
work_dir=/usr/local/var/lib/letsencrypt

root="desuwa.net"

cert=$config_dir/live/$root/cert.pem
chain=$config_dir/live/$root/chain.pem

# --staging
#--dry-run

python -c 'import random; import time; time.sleep(random.random() * 3600)'

certbot renew \
  --quiet \
  --no-eff-email \
  --agree-tos \
  --email "$(get-automation-password certbot-email)" \
  --config-dir $config_dir \
  --logs-dir $logs_dir \
  --work-dir $work_dir
  
sudo /root/nginx-reload.sh

