#! /bin/sh

set -e

pgrep '^manga-syncer$' > /dev/null && exit 1

/usr/local/bin/sqlite3 /usr/home/desuwa/.rss/aw-rss.db "SELECT url FROM feeds WHERE url LIKE 'https://mangadex%' AND disabled = 0;" 2>/dev/null | \
  sed -E 's/.*\/([[:digit:]]+)(\?h=[[:digit:]])?$/\1/' | \
  xargs -L 1 -I {} grep ",{}," /storage/media/manga_map.csv | \
  sed -E 's/.*,([^,]+)$/\1/' | \
  xargs manga-syncer
