#! /bin/sh

#
# sudo mkdir -p /etc/systemd/system/user@.service.d
# cat <<EOF | sudo tee /etc/systemd/system/user@.service.d/delegate.conf
#[Service]
#Delegate=cpu cpuset io memory pids
#EOF
#sudo systemctl daemon-reload

# 8-15, 24-31 is the non-3D CCD
systemctl set-property --runtime -- user.slice AllowedCPUs=8-15,24-31
systemctl set-property --runtime -- system.slice AllowedCPUs=8-15,24-31
systemctl set-property --runtime -- init.scope AllowedCPUs=8-15,24-31
