#!/usr/bin/env bash
set -e
# https://faq.i3wm.org/question/83/how-to-run-i3lock-after-computer-inactivity.1.html

scrot /tmp/screen_locked.bmp
# Needs to be PNG. Optimize appearance then locking speed
convert /tmp/screen_locked.bmp \
  -define png:compression-level=0 \
  -define png:compression-strategy=4 \
  -define png:compression-filter=2 \
  -blur 0x6 /tmp/screen_locked.png

rm -f /tmp/screen_locked.bmp

# Manually locking the screens sets these extremely low
# Keep them low while it's locked
(sleep 30; xset s 600 dpms 600 600 600) &

i3lock -n -i  /tmp/screen_locked.png -e || true

rm -f /tmp/screen_locked.png

wait

xset s 7200 dpms 7200 7200 7200

