#! /bin/sh
# Reliably kill and restart pulse

killall scream-ivshmem-pulse

pulseaudio --kill

while true; do
  pulseaudio --check || break
  sleep 1
done

while true; do
  pulseaudio --check && break
  pulseaudio --start
  sleep 1
done

nohup scream-ivshmem-pulse /dev/shm/scream-ivshmem > /dev/null 2>&1 &
