#!/usr/bin/env bash
# Create a new, empty workspace on every output
# Doesn't handle the case where workspaces with the same names as their outputs
# already exist
set -e

current=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true).output' | cut -d"\"" -f2)


IFS=" "
echo $(i3-msg -t get_workspaces | jq '.[] | select(.visible==true and .output!=.name) | (.name,.output)' | cut -d"\"" -f2) | \
  while read -r name; do
  [ -z "$name" ] && continue
  read -r output
  echo $name $output $current
  [[ "$current" != "$output" ]] && i3-msg workspace "$name"

  echo $output
  i3-msg workspace "$output"
  current=
done

