# You can use the --awconf flag to override the config being loaded.

# Database file. Use :memory: for a temporary, in memory database.
database = "/home/desuwa/.rss/dev.db"

# Host to listen on.
# Do not change this unless you understand the security implications.
# Aw-rss is an unsecured web server; it performs no authentication or
# authorization. If you want to expose aw-rss for remote access it should be
# done using a reverse proxy with basic authentication support such as nginx.
# Change this your own risk.
host = "127.0.0.1"

# Port to listen on.
port = 9092

# Log file, leave blank to log to stdout
# aw-rss truncates this file on every start.
#
# Must be an absolute path if present.
# log_file = "/path/to/file.log"

# Log level, as per RUST_LOG, defaults to Info
# Trace, Debug, Info, Warning, Error
log_level = "Info"

# Whether items with identical URLs should be deduplicated or not, even in
# different feeds.
# When true, items with the same URLs in different feeds will be automatically
# marked as "read" after the first one.
# Whichever feed happens to go first is not deterministic.
dedupe = true
