# Network to connect to MPD on
# unix or tcp are the most likely values
MPDNetwork = 'unix'

# The address to use for MPD
# /path/to/socket or localhost:6600
MPDAddress = '/home/desuwa/.config/mpd/socket'

# Password for MPD
# MPDPassword = ''

# Directory to store the database of tracks
DatabaseDir = '/home/desuwa/.config/mpd-shuffler/db'

# The maximum time between MPD commands in seconds
# Default MPD timeout is 60 seconds, and this must be lower
MPDTimeout = 50

# Regex that songs must match to be included in the rotation
PathRegex = '(Anime/|General/)'

# How many previously played songs to keep on the playlist.
# Doesn't impact the randomization
# Negative values disable this behaviour
KeepLast = 10

# Automatically disable repeat mode
# Repeat mode will effectively disable the shuffler
DisableRepeat = true

# Enable debugging output
# Debug = true
