# Network to connect to MPD on
# unix or tcp are the most likely values
MPDNetwork = 'unix'

# The address to use for MPD
# /path/to/socket or localhost:6600
MPDAddress = '/home/desuwa/.config/mpd/socket'

# Password for MPD
# MPDPassword = ''

# Directory to store the database of tracks
DatabaseDir = '/home/desuwa/.config/mpd-shuffler/db'

# The maximum time between MPD commands in seconds
# Default MPD timeout is 60 seconds, and this must be lower
MPDTimeout = 50

# Regex that songs must match to be included in the rotation
PathRegex = '(Anime/|General/|Zelda/)'

# How many previously played songs to keep on the playlist.
# Doesn't impact the randomization
# Negative values disable this behaviour
KeepLast = 20

# Whether or not to treat newly added songs as not having been played in a
# long time. Set to true to make newly added songs very likely to be played.
NewSongsTreatedAsOld = true

# Automatically disable repeat mode
# Repeat mode will effectively disable the shuffler
DisableRepeat = true

# Lock the volume to 100%
LockVolume = true

# Enable debugging output
# Debug = true
