# The address to use for MPD
# /path/to/socket or localhost:6600
mpd_address = '/home/desuwa/.config/mpd/socket'

# Directory to store the database of tracks
# This will be created if it does not exist, but parent directories won't be.
database = '/home/desuwa/.config/mpd-shuffler/db'

# Regex that song paths must match to be included in the rotation
# Paths are relative to the root of the MPD library.
song_regex = '^(Anime/|General/|Zelda/|Other/)'

# How many previously played songs to keep on the playlist.
# Doesn't impact the randomization
# Negative values disable this behaviour
keep_last = 20

# Automatically disable repeat mode
# Repeat mode will effectively disable the shuffler
disable_repeat = true

# Lock the volume to 100% in case something else is changing it
lock_volume = true

# Disable crossfade in case it was unintentionally enabled.
disable_crossfade = true
