#! /usr/bin/env bash

#**aw-fm-settings-begin**
# name=Interactive Wallpapers
# directories=false
# mimetypes=image/png;image/jpeg;image/bmp
# multiple=false
# priority=-1
#**aw-fm-settings-end**


f=${AWFM_SELECTION%%$'\n'*}

[ -f "$f" ] && alacritty -t aw-i3-forced-float -e wallpapers interactive "$f"

