#! /usr/bin/env bash

#**aw-fm-settings-begin**
# name=Open Terminal
# files=false
# selection=maybe_one
# priority=100
#**aw-fm-settings-end**

d=${AWFM_SELECTION%%$'\n'*}

if [ ! -d "$d" ]; then
  d=$AWFM_CURRENT_TAB_PATH
fi


[ -d "$d" ] && desu-terminal --working-directory "$d"

