#! /usr/bin/env bash

#**aw-fm-settings-begin**
# name=Preview Wallpaper
# directories=false
# mimetypes=image/png;image/jpeg;image/bmp
# multiple=false
# priority=20
#**aw-fm-settings-end**


f=${AWFM_SELECTION%%$'\n'*}

[ -f "$f" ] && wallpapers preview "$f"
