#! /usr/bin/env bash

#**aw-fm-settings-begin**
# name=Open With Xarchiver
# directories=false
# mimetypes=application/zip;application/x-rar;application/x-7z-compressed;application/vnd.comicbook;application/x-tar;application/x-bzip-compressed;application/x-compressed;application/x-zstd-compressed;application/vnd.rar;application/x-lz4-compressed;application/x-lz4-compressed;application/x-xz-compressed
# selection=one
# priority=-2
#**aw-fm-settings-end**

xarchiver "$AWFM_SELECTION"

