#! /usr/bin/env bash

#**aw-fm-settings-begin**
# name=Zip Folders
# files=false
# selection=at_least_one
# priority=200
#**aw-fm-settings-end**

echo "$AWFM_SELECTION" | while IFS=$'\n' read -r f; do
  [ -d "$dir" ] || continue

  base=$(basename "$dir")

  cd "$dir"

  zip -r "../${base}.zip" "." || notify-send "Failed to zip" "$base"
done

notify-send "Done archiving"
