# Port to listen on. You'll need to edit the userscript if you change this.
Port = 8080

# The number of upscaled images to save.
# Don't set this too large as it will waste disk space or memory when using tmpfs.
CacheLimit = 50

# The maximum age of images in the cache.
# Set this to free up memory when using tmpfs.
# Minimum 10
MaxAgeMinutes = 60

# Directory to store temporary files, leave blank for the system default temp directory
# TempDirectory = 'C:\temp'

# Where to find waifu2x-ncnn-vulkan.
# If uncommented this takes precedence over waifu2x-converter-cpp and waifu2x-caffe
Waifu2xNCNNVulkan = 'waifu2x-ncnn-vulkan'

# The path to the chosen model for waifu2x-ncnn-vulkan.
# The CUNET model is recommended for quality.
# Speed is of minimal importance since all wallpapers are cached.
Waifu2xNCNNVulkanModels = '/storage/src/third_party/waifu2x-ncnn-vulkan/models/models-cunet'

# Uncomment to allow cloudscraper to work to attempt to bypass cloudflare.
# Cloudscraper = true

